[".local/share/oh-my-zsh"]
type            = "archive"
url             = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
exact           = true
stripComponents = 1
refreshPeriod   = "72h"

[".config/oh-my-zsh/plugins/zsh-autosuggestions"]
type            = "archive"
url             = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
exact           = true
stripComponents = 1
refreshPeriod   = "72h"

[".config/oh-my-zsh/plugins/zsh-history-substring-search"]
type            = "archive"
url             = "https://github.com/zsh-users/zsh-history-substring-search/archive/master.tar.gz"
exact           = true
stripComponents = 1
refreshPeriod   = "72h"

[".config/oh-my-zsh/plugins/zsh-syntax-highlighting"]
type            = "archive"
url             = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
exact           = true
stripComponents = 1
refreshPeriod   = "72h"

# See https://huggingface.co/ggerganov/whisper.cpp/blob/main/ggml-small.bin for more information
[".local/share/whisper/ggml-small.bin"]
type            = "file"
url             = "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.bin"
refreshPeriod   = "672h"
checksum.sha256 = "1be3a9b2063867b937e64e2ec7483364a79917e157fa98c5d94b5c1fffea987b"
